export enum ActionTypes {
    SHOW_BOARD = 'SHOWBOARD',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    FORMDATA = 'FORMDATA',
    FORMDATADELETE = 'FORMDATADELETE',
    GET_ID_TO_VIEW_BOARD = 'GET_ID_TO_VIEW_BOARD',
    ADDPOSTTOBOARD = 'ADDPOSTTOBOARD',
    REMOVEPOSTFROMBOARD = 'REMOVEPOSTFROMBOARD',
    FETCH_DATA = 'FETCH_DATA',
    IS_LOADING='IS_LOADING'
}