export enum ActionTypes {
    SHOW_BOARD = 'SHOWBOARD',
    SHOW_IMAGE_MODAL='SHOW_IMAGE_MODAL',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    FORMDATA = 'FORMDATA',
    FORMDATADELETE = 'FORMDATADELETE',
    GET_ID_TO_VIEW_BOARD = 'GET_ID_TO_VIEW_BOARD',
    ADDREMOVEPOSTTOBOARD = 'ADDREMOVEPOSTTOBOARD',
    FETCH_DATA = 'FETCH_DATA',
    IS_LOADING='IS_LOADING',
    ADDIMAGETOBOARDLOADER='ADDIMAGETOBOARDLOADER'
}